[pytest]
testpaths = tests
addopts = -ra --strict-markers

markers =
    login: Pruebas relacionadas con inicio de sesión.
    catalogo: Pruebas relacionadas con navegación y verificación del catálogo.
    carrito: Pruebas relacionadas con interacción de productos y carrito.
    smoke: Pruebas críticas y rápidas.